# Generated by Django 3.2.7 on 2021-10-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='task_details',
            new_name='assignment_details',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='upload_assignment',
        ),
    ]
