# Generated by Django 3.2.7 on 2021-10-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20211006_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Registered Student', 'verbose_name_plural': 'Registered Students'},
        ),
        migrations.AddField(
            model_name='assignment',
            name='upload_assignment',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
