# Generated by Django 3.2.7 on 2021-10-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_submissions_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isStudent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='isTeacher',
            field=models.BooleanField(default=True),
        ),
    ]
